spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.39.179:3305/honey-oss?useUnicode=true&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: yangzhijie@cvte.com
  application:
    name: honey-oss-server
  servlet:
    multipart:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/META-INF/mapper/*.xml
honey:
  oss:
    callback-type: 0
    appId: 2157104550
    appKey: v7FCd5UZOyRqNxSL
    minio:
      url: http://192.168.200.211:9000
      accesskey: HONEYOSS
      secretkey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      bucketName: honey-oss-dev
dubbo:
  scan:
    base-packages: red.honey.oss.server
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    protocol: zookeeper
    address: zookeeper://49.235.208.98:2181
  application:
    name: honey-oss-server
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  page-size-zero: false
  params: count=countSql