spring:
  application:
    name: honey-oss-job

xxl:
  job:
    accessToken:
    admin:
      addresses: http://localhost:8088/xxl-job-admin
    executor:
      appname: xxl-job-honey-oss-identify
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9090
honey:
  oss:
    app_id: 2157104550
    app_key: v7FCd5UZOyRqNxSL

server:
  port: 8089
