spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.39.179:3305/honey-oss?useUnicode=true&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: yangzhijie@hooney.red
  application:
    name: honey-oss-admin
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/META-INF/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  page-size-zero: false
  params: count=countSql
